version: '2'
services:
    glory80-app:
        image: glory80
        external_links:
            - glory80-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/glory80?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    glory80-mysql:
        extends:
            file: mysql.yml
            service: glory80-mysql
